### ISSUE TITLE
Lidiar con casos donde d>p

### ISSUE THREAD

**Issue by acarril** [acarril/device-patterns#1]
Actualmente, en múltiples instancias del _stack_ (i.e. métodos de clase, API, _front_) se asume que $d < p$, es decir, que hay menos dispositivos que plantas. Sin embargo, existen situaciones donde $d > p$, y deben instalarse múltiples dispositivos por planta.

Queda pendiente generalizar el problema a nivel del algoritmo, y además idear una forma de comunicar este tipo de patrones efectivamente.

**Comment by nortuzar** [comment]
Ejemplo de instalación donde cada **x** representa un emisor
![Captura de pantalla 2023-07-24 114556](https://github.com/acarril/device-patterns/assets/55258023/3c01a23e-cce8-474c-887e-3453c85ab650)

**Comment by nortuzar** [comment]
Otro caso como ejemplo
![Captura de pantalla 2023-07-27 150500](https://github.com/acarril/device-patterns/assets/55258023/1f5316ed-ce5e-4482-92ef-721a4298c5b1)

**Comment by nortuzar** [comment]
Otro caso como ejemplo
![Captura de pantalla 2023-07-27 150500](https://github.com/acarril/device-patterns/assets/55258023/72bfcb39-a4ec-42a8-9b79-7626734cd327)
