### ISSUE TITLE
Mostrar patrones verticalmente

### ISSUE THREAD

**Issue by acarril** [acarril/device-patterns#11]
En #8 @nortuzar comenta que sería ideal mostrar los patrones de forma vertical (i.e. como columnas). Actualmente son horizontales (ver imagen).

<img width="402" alt="image" src="https://github.com/acarril/device-patterns/assets/9773292/6103f6d1-d803-49fd-a336-5f045a9915f8">

**Comment by nortuzar** [comment]
Lo voy a cerrar ya que al no generar el formato para copiarlo a excel no vale la pena trabajar para que se vea vertical
