### ISSUE TITLE
Necesidades post reunion SAG

### ISSUE THREAD

**Issue by nortuzar** [acarril/device-patterns#15]
1. Restricciones SAG no son necesarias, por lo que la solución puede estar compuesta por un espacio más amplio. No limitarse a patrones consecutivos y permitir que el espacio solución pueda usar hasta 3 patrones distintos y no consecutivos. Ejemplos: 1/2, 1/4  O  1/3, 1/5, 1/6. Limitar los patrones a diferir solo en uno (1/3,1/5)
2. Tolerancia hacia abajo variable según densidad buscada (d_min). Ej: si d_min==500, aplicar 4% hacia abajo en búsqueda de un patrón simple. Finalmente jugar con tolerancia hacia arriba y hacia abajo en búsqueda de la solución óptima 
3. Dar una solución única, no dos como se planteó inicialmente.  
4. Buscar método para priorizar solución que se acerque lo más a d_min a través de la sub tolerancia (para d_min=200, es mejor 198 que 202)

**Comment by acarril** [comment]
Buena. Creo que voy a dejarlo en issues separados para ir trackeando/resolviendo individualmente.

**Comment by acarril** [comment]
1. #16 
2. 

> 1. Restricciones SAG no son necesarias, por lo que la solución puede estar compuesta por un espacio más amplio. No limitarse a patrones consecutivos y permitir que el espacio solución pueda usar hasta 3 patrones distintos y no consecutivos. Ejemplos: 1/2, 1/4  O  1/3, 1/5, 1/6. Limitar los patrones a diferir solo en uno (1/3,1/5)
> 
>     2. Tolerancia hacia abajo variable según densidad buscada (d_min). Ej: si d_min==500, aplicar 4% hacia abajo en búsqueda de un patrón simple. Finalmente jugar con tolerancia hacia arriba y hacia abajo en búsqueda de la solución óptima
> 
>     3. Dar una solución única, no dos como se planteó inicialmente.
> 
>     4. Buscar método para priorizar solución que se acerque lo más a d_min a través de la sub tolerancia (para d_min=200, es mejor 198 que 202)

1. #16 
2. #17
3. #18
4. #17
