### ISSUE TITLE
Mostrar únicamente solución que minimiza densidad

### ISSUE THREAD

**Issue by acarril** [acarril/device-patterns#4]
En la práctica, la solución que minimiza densidad es la única que es de interés. Debe eliminarse del front la segunda solución (min. hileras).

**Comment by nortuzar** [comment]
Dejemolo como está, por último despues si se necesita lo saco del front, no creo que sea dificil

**Comment by acarril** [comment]
> Dejemolo como está, por último despues si se necesita lo saco del front, no creo que sea dificil

Sí, es botado.
