### ISSUE TITLE
Caso borde, no encuentra solución

### ISSUE THREAD

**Issue by nortuzar** [acarril/device-patterns#7]
Al utilizar p=952 , d=500 y max de hileras <=11, el sistema funciona. Al aumentar el max de hileras a 12 o más, se queda pegado "pensando"
![Captura de pantalla 2023-07-24 115022](https://github.com/acarril/device-patterns/assets/55258023/c537f3c9-7c08-477a-aaee-6b9e2d8295e4)

**Comment by acarril** [comment]
En una situación similar, hay casos donde la respuesta de la API es vacía y no se entrega ningún resultado. Sería mejor manejar ambos casos explícitamente.

<img width="853" alt="image" src="https://github.com/acarril/device-patterns/assets/9773292/2273262f-07ca-4c77-a142-26cd8bc54fc9">

**Comment by acarril** [comment]
Este problema se solucionó en b731303; este comentario es para dejar documentadas las circunstancias que generan el problema y la solución implementada.

La causa superficial del problema es que no se manejaba de manera explícita un error en la API. b731303 hace las modificaciones para entregar explícitamente un valor `null` cuando no se encuentra una solución, y el _front_ ahora maneja esta respuesta de la API y reporta un mensaje acorde. 

<img width="553" alt="image" src="https://github.com/acarril/device-patterns/assets/9773292/a6fd034b-c016-43b8-8378-51ddf080ca67">

**La raíz del problema es que no se encuentra solución con los parámetros ingresados. Esto va a ser usual cuando la dosis mínima sea mayor que la mitad del número de plantas** (i.e. cuando $0.5 < r < 1$), ya que una de las restricciones es que no se pueden usar patrones que representen fracciones entre 0.5 y 1. Por ejemplo, "dos emisores cada tres plantas", o sea 2/3, no es un patrón admisible.

Esta restricción de los patrones fuerza al algoritmo a encontrar una combinación de hileras con patrones de $0.5$ y $1$, respectivamente. Esto tiene como consecuencia que la densidad de las soluciones será mucho más alta que la densidad mínima, a menos que se permita un número muy grande de hileras. Buscar soluciones con un número alto de hileras es computacionalmente muy costoso.

<img width="527" alt="image" src="https://github.com/acarril/device-patterns/assets/9773292/1c1e3c4f-5f23-4e50-acff-0e7c49c6f26d">
